### PR TITLE
Add a page to query pixel data from the database

### PR DESCRIPTION
**Pull request by netux**
image

My goal was to facilitate pixel lookups for mods. This page allows them to filter pixels by time, coordinate range, placers, color, most recent, mod action, etc.

### TODO:
- [x] Implement search functionality
  - [x] by coordinate
  - [x] by coordinate range
  - [x] by time range
  - [x] by users
  - [x] by color
  - [x] by boolean properties (mod action, most recent, undo action, etc.)
- [x] Implement a canvas to easily visualize the results
  - [x] basic functionality
  - [x] with a way to manipulate which pixels are drawn
  - [x] with a "color-coded users" mode
- [ ] Test for attack vectors (SQL injection, XSS)

### CODE REVIEW

**Comment by netux** [comment]
Barebones board preview
image

**Comment by netux** [comment]
New placers dynamic list:
image

Color-coded mode:
image

**Comment by netux** [comment]
Range sliders on board preview
image

**Comment by netux** [comment]
Been working on this for a while and I think its at a point where it can be shipped.

I'd love to add more things like graphs similar to the ones on [PxlsFiddle's stats page](https://pxlsfiddle.com/statsgraph), but maybe its best to get this out now and add things on future PRs.

The last thing to do here is to test for attack vectors (SQL injections, XSS, and the like). I'm not the best with PHP and I worry I left some in there 😅. I'll leave it to the reviewer(s) to try and find any vulnerabilities I've missed.

**Comment by JewishLewish** [comment]
Question:
Will it be possible for Discord Bot Coders to access specific information to place info into their bots to allow access a lot smoother/easier for the average pxls.space player? 
In addition, can you give a list of information that can be given to an average pxls.space player that they can find on here?

**Comment by netux** [comment]
> Question:
> Will it be possible for Discord Bot Coders to access specific information to place info into their bots to allow access a lot smoother/easier for the average pxls.space player?
> In addition, can you give a list of information that can be given to an average pxls.space player that they can find on here?

No, everything here is for the admin panel and will only be available for staff members.

There are no plans to release this information for everyone to see/use.

**Comment by JewishLewish** [comment]
It's so cool and useful.
Can you consider giving some JSON information please.
I see no harming leaking it to the public

**Pull request merged**
